// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xghbroyvszfuvqonhbln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnaGJyb3l2c3pmdXZxb25oYmxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDI3ODcsImV4cCI6MjA2MTIxODc4N30.p3k3YUr9pBNu7vfN7ErXq2tFkSOvxvX2bsWKIgMTMX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);